# Site settings
title: New York Tai Chi
email: your-email@domain.com
url: https://nogre.github.io
description: "Master Yao Wah Chan, a distinguished Tai Chi instructor with over 45 years teaching experience, is pleased to offer a new program designed for the modern office. Drawing from various Internal Arts, including Tai Chi, Qi Gong, and Bagua Zang, classes will boost energy and fitness with minimal physical impact."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: New York Tai Chi

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: 
  - title: facebook
    url:
  - title: linkedin
    url: 

# Build settings
markdown: kramdown
permalink: pretty
